In [ ]:
import numpy as np





---



**Ejercicio #1-C2  Datasets sintético**

En problemas de Machine Learning es muy importante contar con el dataset correcto. Pero muchas veces, el dataset no es fácil conseguir o el equipo de data engineers aún lo está generando.

Una manera sencilla de generar datos para probar soluciones de Machine Learning es crear datasets sintéticos. Por ejemplo, es simple crear datasets con grados de clusterización variables y probar cómo se comportan nuestros algoritmos en diferentes escenarios. 

Objetivo: utilizar numpy para crear datos clusterizados A/B en 4 dimensiones.

Hint:



*   Definir una matriz de centroides [1,0,0,0] y [0,1,0,0]
*   Utilizar una constante para separar o alejar los centroides entre si.
*   Utilizar np.repeat para crear n/2 muestras de cada centroide.
*   Sumar a cada centroide un vector aleatorio normal i.i.d. con media 0 y desvío (np.random.normal)

*   Armar un arreglo que tenga n enteros indicando si la muestra pertenece a A o a B








In [ ]:
import numpy as np
class DatasetSintetico(object):

  def matrizDeCentroides(self,constante):
    arr1=np.array([1,0,0,0])
    arr2=np.array([0,1,0,0])
    matriz=np.matrix((arr1,arr2))
    matriz=np.multiply(matriz,constante)
    return matriz

  def datos(self, numDatos):
    cent=self.matrizDeCentroides(constante)
    data=np.repeat(cent,numDatos/2,axis=0)
    return data

  def desvest_generador(self,numDatos):
    media=0
    desvest=np.random.normal(loc=media,scale=1,size=(numDatos,4))
    return desvest

  def respFinal(self,numDatos):
    #Lo corro una vez por cluster:
    datosA=self.datos(numDatos)
    desvestA=self.desvest_generador(numDatos)
    vectorAleatorioA=datosA+desvestA
    #0 Representa el Cluster A
    vectorAleatorioA[5,:]=0
    datosB=self.datos(numDatos)
    desvestB=self.desvest_generador(numDatos)
    vectorAleatorioB=datosB+desvestB
    #1 Representa el Cluster B
    vectorAleatorioA[5,:]=1
    respuestaFinal=np.vstack((vectorAleatorioA,vectorAleatorioB))
    return respuestaFinal
#Creo una nueva instancia
dt=DatasetSintetico()

#Creo la constante que va a separar o acercar los centroides
constante=2

#Indico cuántos datos necesito
datos=1000

print(dt.respFinal(datos))

[[ 3.16157209 -0.96057197  0.37335445  0.71020885]
 [ 0.47884511 -0.70912936  0.70352921 -0.16304079]
 [ 2.66970981 -0.74228334  1.11645347  1.92848938]
 ...
 [-0.80269634  0.22250967 -0.71559753  0.97591323]
 [-0.33155228  2.76831632  0.88315121 -0.24547869]
 [ 0.10539838  1.02185298  0.69370816  0.77123347]]




---



**Ejercicio #1 Dado un dataset X, calcular PCA para reducir dimensión**

Siguiendo los pasos vistos en la teoría, se requiere utilizar numpy para calcular PCA del dataset de entrada X, utilizando los componentes más importantes.

                     x= np.array([[0.8, 0.7] , [0.1, -0,1]])

 Al finalizar la implementación en numpy, corroborar obtener los mismos resultados que utilizando el código de la librería scikit-learn. Escribir un test para comprobar las matrices.                 

In [ ]:
#Importamos las librerías necesarias para poder hacer la comparación con Sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

1. Dado un dataset con n muestras y d features, queremos reducir sus diemnsiones a m. Para ello, el primer paso es centrar el dataset.
2. Obtener la matriz de covarianza X Transpuesta.
3. Calcular los autovalores y autovectores de la matriz de covarianza. Revisar la documentación de Numpy.
4. Ordenar los autovalores y autovectores de la matriz de covarianza.
5. Ordenar los autovectores en el sentido de los autovalores decrecientes.
6. Proyectar el dataset centrado sobre los m autocetores más relevantes usando np.dot.
7. Consolidar los pasos anteriores en una función

In [ ]:
#Definimos el dataset
x=np.array([[0.8,0.7],[0.1,-0.1]])
print(x)

def pca(x):
  #Centramos el dataset
  xMedia=np.mean(x,axis=0)
  xCentrado=x-xMedia

  #Trasponemos la matriz xCentrada
  transpuesta=np.matrix.transpose(xCentrado)
  covarianza=np.cov(transpuesta)

  #Calculamos los Eigenvalues y Eigenvectors
  eigenValores, eigenVectores = np.linalg.eig(covarianza)

  #Organizamos los autovalores y autovectores.
  #Sort regresa la lista organizada, mientras que argsort regresa los índices.
  eigenValoresS=np.argsort(eigenValores)
  eigenVectoresS=np.argsort(eigenVectores)

  #Ahora los organizamos de mayor a menor
  eigenValoresS2=eigenValoresS[::-1]
  eigenVectoresS2=eigenVectoresS[::-1]

  #Finalmente, proyectamos usando np.dot
  proy=np.dot(xCentrado,eigenVectoresS2)
  print(proy)

k=pca(x)

[[ 0.8  0.7]
 [ 0.1 -0.1]]
[[ 0.8  0.7]
 [ 0.1 -0.1]]




---



**Ejercicio #2  Aplicar PCA y K-means al datasets de dígitos**

Siguiendo los ejemplos vistos en clase sobre los datasets del Human Activity Recognition y Fashion MNIST, realizar las siguientes consignas:



1.   Aplicar PCA sobre el dataset para poder explicar el 90% de la varianza. ¿cuántos componentes se requieren?
2.  Graficar un screen plot ( varianza contemplada en función del número de componentes considerados)
3. Visualizar gráficamente los primeros 5 componentes ¿Qué conclusiones se puede sacar de cada componente? [OPCIONAL]
4. Visualizar la imágen original vs la reconstruida con los m componentes del punto 1.
5. Graficar una matriz de correlación del dataset reducido.
6. Graficar los clusters de dígitos en 2 y 3 dimensiones usando los componentes obtenidos en PCA.
7. Aplicar K-means para clusterizar los dígitos ¿cómo son los resultados?
8.Realizar un gráfico de inercia para obtener el número óptimo de clusters *K.*
9. Analizar visualmente los límites de cluster de algún dígito y "generar" artificialmente el dígito dándole valores a los primeros dos componentes de PCA.


In [ ]:
#Según lo dado en el ejemplo Fashion MNIST
# Cargamos los datos de training
X, y = load_digits(return_X_y=True)
print('Formato del dataset: {}'.format(X.shape))



---



**Ejercicio integrador**

1. Generar un dataset sintético con una función seno (pueden usar otras funciones no lineales)
2. Hacer el gráfico de los datos
3. Hacer fit con la solución cerrada de regresión lineal y con los algoritmos de descenso por el gradiente vistos en clase, para diferentes polinomios hasta el orden 15. Comenten los problemas numéricos encontrados.
4. Obtener mediante cross-validation para cada polinomio el error de validación.
5. Seleccionar el modelo con complejidad correcta para el dataset.
6. Regularizar el modelo y comparar los resultados.